-- This text is generated by TrigEditPlus
function MEME_ClassicTrig()

Trigger {
	players = {P8},
	conditions = {
		Always();
	},
	actions = {
		--RunAIScriptAt("Send All Units on Random Suicide Missions", "Anywhere");
		RunAIScriptAt("Zerg Campaign Insane", "Anywhere");
		--RunAIScriptAt("Move Dark Templars to Region", "Anywhere");
		--RunAIScriptAt("Send All Units on Strategic Suicide Missions", "Anywhere");
	},
}






Trigger {
	players = {Force2},
	conditions = {
		Always();
	},
	actions = {
		--ModifyUnitHangarCount(8, All, "Gantrithor (Carrier)", AllPlayers, "Anywhere");
		--ModifyUnitHangarCount(10, All, "Warbringer (Reaver)", AllPlayers, "Anywhere");
		SetInvincibility(Enable, "Protoss Interceptor", AllPlayers, "Anywhere");
		SetInvincibility(Enable, "Vulture Spider Mine", AllPlayers, "Anywhere");
		PreserveTrigger();
	},
}





Trigger { -- HM
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, AtLeast, 1, "Terran Marine", "Hero");
		Accumulate(CurrentPlayer, AtLeast, 15000, Ore);
	},
	actions = {
		PreserveTrigger();
		RemoveUnitAt(1, "Terran Marine", "Hero", CurrentPlayer);
		SetDeaths(CurrentPlayer, Add, 1, "Terran Ghost");
		SetResources(CurrentPlayer, Subtract, 15000, Ore);
		CreateUnit(1, "Jim Raynor (Marine)", "HZ", CurrentPlayer);
		Comment("HM");
	},
}
Trigger { -- PM
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, AtLeast, 1, 20, "Hero");
		Accumulate(CurrentPlayer, AtLeast, 25000, Ore);
	},
	actions = {
		PreserveTrigger();
		RemoveUnitAt(1, 20, "Hero", CurrentPlayer);
		SetResources(CurrentPlayer, Subtract, 25000, Ore);
		CreateUnit(1, 99, "HZ", CurrentPlayer);
		Comment("HM");
	},
}


Trigger { -- BBX
	players = {Force1},
	conditions = {
		Always();
	},
	actions = {
		SetInvincibility(Enable, "Terran Medic", CurrentPlayer, "Anywhere");
		RunAIScript("Turn ON Shared Vision for Player 1");
		RunAIScript("Turn ON Shared Vision for Player 2");
		RunAIScript("Turn ON Shared Vision for Player 3");
		RunAIScript("Turn ON Shared Vision for Player 4");
		RunAIScript("Turn ON Shared Vision for Player 5");
		RunAIScript("Turn ON Shared Vision for Player 6");
		SetAllianceStatus(Force1, Ally);
		SetAllianceStatus(P6, Ally);
		PreserveTrigger();
		Comment("BBX");
	},
}
Trigger { -- 
	players = {P6},
	conditions = {
		Always();
	},
	actions = {
		RunAIScript("Turn ON Shared Vision for Player 1");
		RunAIScript("Turn ON Shared Vision for Player 2");
		RunAIScript("Turn ON Shared Vision for Player 3");
		RunAIScript("Turn ON Shared Vision for Player 4");
		RunAIScript("Turn ON Shared Vision for Player 5");
		SetAllianceStatus(Force1, Ally);
		PreserveTrigger();
	},
}


Trigger {
	players = {Force1},
	actions = {
		SetResources(CurrentPlayer, Add, 20000, Ore);
	},
}


Trigger {
	players = {Force2},
	actions = {
		SetResources(CurrentPlayer, Add, 9999999, Ore);
		SetResources(CurrentPlayer, Add, 9999999, Gas);
	},
}


Trigger { -- MH
	players = {Force1},
	conditions = {
		Command(CurrentPlayer, AtLeast, 1, "Terran Medic");
	},
	actions = {
		PreserveTrigger();
		RemoveUnit("Terran Medic", CurrentPlayer);
		ModifyUnitHitPoints(All, "Men", CurrentPlayer, "Anywhere", 100);
		ModifyUnitShields(All, "Men", CurrentPlayer, "Anywhere", 100);
		Comment("MH");
	},
}



Trigger { -- HZD
	players = {Force1},
	conditions = {
		Always();
	},
	actions = {
		PreserveTrigger();
		SetDeaths(CurrentPlayer, Add, 1, "Zerg Zergling");
		Comment("HZD");
	},
}


Trigger { -- HZ
	players = {Force1},
	conditions = {
		Deaths(CurrentPlayer, AtLeast, 51, "Zerg Zergling");
	},
	actions = {
		PreserveTrigger();
		ModifyUnitHitPoints(All, "Men", CurrentPlayer, "HZ", 100);
		ModifyUnitShields(All, "Men", CurrentPlayer, "HZ", 100);
		SetDeaths(CurrentPlayer, SetTo, 0, "Zerg Zergling");
		Comment("HZ");
	},
}





Trigger { -- XELD
	players = {P8},
	conditions = {
		Bring(P8, Exactly, 0, "Xel'Naga Temple", "CD63");
	},
	actions = {
		PreserveTrigger();
		SetDeaths(P6, Add, 1, "Protoss Archon");
		Comment("XELD");
	},
}





Trigger {
	players = {P8},
	conditions = {
		Bring(P8, Exactly, 0, "Zerg Sunken Colony", "CD11");
	},
	actions = {
		CreateUnit(12, "Edmund Duke (Siege Mode)", "ECB4", P8);
		CreateUnit(12, "Edmund Duke (Siege Mode)", "ECB3", P8);
	},
}



Trigger { -- SHD1
	players = {P8},
	conditions = {
		Bring(P8, Exactly, 0, "Zerg Sunken Colony", "CD49");
	},
	actions = {
		CreateUnit(15, "Edmund Duke (Siege Mode)", "CD229", P8);
		Comment("SHD1");
	},
}


Trigger { -- SHD2
	players = {P8},
	conditions = {
		Bring(P8, Exactly, 0, "Zerg Sunken Colony", "CD57");
	},
	actions = {
		CreateUnit(15, "Edmund Duke (Siege Mode)", "CD230", P8);
		Comment("SHD2");
	},
}


Trigger { -- SHD3
	players = {P8},
	conditions = {
		Bring(P8, Exactly, 0, "Zerg Sunken Colony", "CD32");
	},
	actions = {
		CreateUnit(15, "Edmund Duke (Siege Mode)", "CD73", P8);
		Comment("SHD3");
	},
}


Trigger { -- TBH
	players = {P8},
	conditions = {
		Bring(P8, Exactly, 0, "Terran Bunker", "ECB5");
	},
	actions = {
		CreateUnit(15, "Edmund Duke (Siege Mode)", "CD36", P8);
		Comment("TBH");
	},
}


Trigger { -- MMM
	players = {P6},
	conditions = {
		Always();
	},
	actions = {
		SetDeaths(P6, Subtract, 1, "Zerg Creep Colony");
		PreserveTrigger();
		Comment("MMM");
	},
}


Trigger { -- MMM1
	players = {P6},
	conditions = {
		Deaths(P6, Exactly, 0, "Zerg Creep Colony");
	},
	actions = {
		PreserveTrigger();
		SetDeaths(P6, SetTo, 650, "Zerg Creep Colony");
		Order("Men", P8, "MMM", Attack, "HZ");
		Order("Men", P7, "MMM", Attack, "HZ");
		Comment("MMM1");
	},
}




Trigger {
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, Exactly, 1, "Devouring One (Zergling)", "1P");
		Accumulate(CurrentPlayer, AtLeast, 50000, Ore);
	},
	actions = {
		SetResources(CurrentPlayer, Subtract, 50000, Ore);
		SetResources(P1, Add, 50000, Ore);
		MoveUnit(1, "Devouring One (Zergling)", CurrentPlayer, "1P", "GiveRe");
		DisplayText("\x13\x04 Give \x0750000 \x04Ore", 4);
		PreserveTrigger();
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, Exactly, 1, "Devouring One (Zergling)", "2P");
		Accumulate(CurrentPlayer, AtLeast, 50000, Ore);
	},
	actions = {
		SetResources(CurrentPlayer, Subtract, 50000, Ore);
		SetResources(P2, Add, 50000, Ore);
		MoveUnit(1, "Devouring One (Zergling)", CurrentPlayer, "2P", "GiveRe");
		DisplayText("\x13\x04 Give \x0750000 \x04Ore", 4);
		PreserveTrigger();
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, Exactly, 1, "Devouring One (Zergling)", "3P");
		Accumulate(CurrentPlayer, AtLeast, 50000, Ore);
	},
	actions = {
		SetResources(CurrentPlayer, Subtract, 50000, Ore);
		SetResources(P3, Add, 50000, Ore);
		MoveUnit(1, "Devouring One (Zergling)", CurrentPlayer, "3P", "GiveRe");
		DisplayText("\x13\x04 Give \x0750000 \x04Ore", 4);
		PreserveTrigger();
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, Exactly, 1, "Devouring One (Zergling)", "4P");
		Accumulate(CurrentPlayer, AtLeast, 50000, Ore);
	},
	actions = {
		SetResources(CurrentPlayer, Subtract, 50000, Ore);
		SetResources(P4, Add, 50000, Ore);
		MoveUnit(1, "Devouring One (Zergling)", CurrentPlayer, "4P", "GiveRe");
		DisplayText("\x13\x04 Give \x0750000 \x04Ore", 4);
		PreserveTrigger();
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Bring(CurrentPlayer, Exactly, 1, "Devouring One (Zergling)", "5P");
		Accumulate(CurrentPlayer, AtLeast, 50000, Ore);
	},
	actions = {
		SetResources(CurrentPlayer, Subtract, 50000, Ore);
		SetResources(P5, Add, 50000, Ore);
		MoveUnit(1, "Devouring One (Zergling)", CurrentPlayer, "5P", "GiveRe");
		DisplayText("\x13\x04 Give \x0750000 \x04Ore", 4);
		PreserveTrigger();
	},
}


Trigger {
	players = {P1},
	conditions = {
		Bring(P1, AtLeast, 1, "Unclean One", "1P");
	},
	actions = {
		KillUnit("Any unit", P1);
		Defeat();
	},
}

Trigger {
	players = {P2},
	conditions = {
		Bring(P1, AtLeast, 1, "Unclean One", "2P");
	},
	actions = {
		KillUnit("Any unit", P2);
		Defeat();
	},
}


Trigger {
	players = {P3},
	conditions = {
		Bring(P1, AtLeast, 1, "Unclean One", "3P");
	},
	actions = {
		KillUnit("Any unit", P3);
		Defeat();
	},
}


Trigger {
	players = {P4},
	conditions = {
		Bring(P1, AtLeast, 1, "Unclean One", "4P");
	},
	actions = {
		KillUnit("Any unit", P4);
		Defeat();
	},
}


Trigger {
	players = {P5},
	conditions = {
		Bring(P1, AtLeast, 1, "Unclean One", "5P");
	},
	actions = {
		KillUnit("Any unit", P5);
		Defeat();
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Always();
	},
	actions = {
		KillUnit("Men", P12);
		KillUnit("Terran Barracks", P12);
		KillUnit("Terran Comsat Station", P12);
		KillUnit("Terran Engineering Bay", P12);
		KillUnit("Terran Missile Turret", P12);
		KillUnit("Terran Bunker", P12);
		KillUnit("Zerg Beacon", P12);
		KillUnit("Protoss Beacon", P12);
		KillUnit("Terran Beacon", P12);
		PreserveTrigger();
	},
}



Trigger {
	players = {Force2},
	conditions = {
		Always();
	},
	actions = {
		SetDeaths(P6, Add, 1, "Zerg Marker");
		PreserveTrigger();
	},
}


Trigger {
	players = {Force2},
	conditions = {
		Deaths(P6, Exactly, 2, "Zerg Marker");
	},
	actions = {
		ModifyUnitShields(All, "Stasis Cell/Prison", P8, "Anywhere", 100);
		ModifyUnitShields(All, "Power Generator", P8, "Anywhere", 100);
		ModifyUnitShields(All, "Xel'Naga Temple", P8, "Anywhere", 100);
		ModifyUnitShields(All, "Protoss Temple", P8, "Anywhere", 100);
		ModifyUnitShields(All, "Protoss Nexus", P8, "Anywhere", 100);
		ModifyUnitShields(All, "Protoss Stargate", P8, "Anywhere", 100);
		PreserveTrigger();
	},
}


Trigger {
	players = {Force2},
	conditions = {
		Deaths(P6, Exactly, 3, "Zerg Marker");
	},
	actions = {
		SetDeaths(P6, SetTo, 0, "Zerg Marker");
		PreserveTrigger();
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Command(P7, Exactly, 0, "Any unit");
		Command(P8, Exactly, 0, "Any unit");
	},
	actions = {
		Victory();
	},
}




Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Zerg Overmind (With Shell)");
		Command(P8, Exactly, 0, "Protoss Nexus");
		Command(P8, Exactly, 0, "Stasis Cell/Prison");
		Command(P8, Exactly, 0, "Psi Disrupter");
		Command(P8, Exactly, 0, "Infested Command Center");
		Command(P8, Exactly, 0, "Ion Cannon");
	},
	actions = {
		SetInvincibility(Disable, "Mature Crysalis", P8, "Anywhere");
	},
}




Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Zerg Lair");
		Command(P7, Exactly, 0, "Zerg Lair");
	},
	actions = {
		SetInvincibility(Disable, "Warp Gate", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Zerg Hatchery");
		Command(P7, Exactly, 0, "Zerg Hatchery");
		Command(P8, Exactly, 0, "Terran Command Center");
	},
	actions = {
		SetInvincibility(Disable, "Zerg Overmind", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Zerg Overmind");
	},
	actions = {
		SetInvincibility(Disable, "Psi Disrupter", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Warp Gate");
		Command(P8, Exactly, 0, "Norad II (Crashed Battlecruiser)");
		Command(P8, Exactly, 0, "Stasis Cell/Prison");
		Command(P8, Exactly, 0, "Protoss Nexus");
	},
	actions = {
		SetInvincibility(Disable, "Zerg Overmind (With Shell)", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Norad II (Crashed Battlecruiser)");
	},
	actions = {
		SetInvincibility(Disable, "Stasis Cell/Prison", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Zerg Hive");
		Command(P7, Exactly, 0, "Zerg Hive");
	},
	actions = {
		SetInvincibility(Disable, "Norad II (Crashed Battlecruiser)", P8, "Anywhere");
		SetInvincibility(Disable, "Infested Command Center", P7, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Stasis Cell/Prison");
	},
	actions = {
		SetInvincibility(Disable, "Protoss Stargate", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Protoss Stargate");
		Command(P8, Exactly, 0, "Infested Command Center");
		Command(P7, Exactly, 0, "Infested Command Center");
	},
	actions = {
		SetInvincibility(Disable, "Protoss Nexus", P8, "Anywhere");
	},
}


Trigger {
	players = {P8},
	conditions = {
		Command(P8, Exactly, 0, "Terran Armory");
	},
	actions = {
		SetInvincibility(Disable, "Infested Command Center", P8, "Anywhere");
	},
}


Trigger {
	players = {Force1},
	conditions = {
		Always();
	},
	actions = {
		SetMissionObjectives("\r\n\x13 Firebat > BGM On/Off\r\n\x13 Terran Marine > Jim Rayner 15000 Ore \r\n\x13 Jim Rayner > Samir Duran 25000 Ore\r\n\x13 Ghost > Jim Rayner 20000 Ore \r\n\x13 Currency Exchange > 7 o'clock mineral \r\n\x13 Bunker MAX 8 \r\n\x13 currency exchange rate 28%\x1F");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 140);
	},
	actions = {
		CreateUnit(12, "Devouring One (Zergling)", "HZ", P8);
		CreateUnit(12, "Devouring One (Zergling)", "Hero", P8);
		Order("Devouring One (Zergling)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 360);
	},
	actions = {
		CreateUnit(12, "Hunter Killer (Hydralisk)", "HZ", P8);
		CreateUnit(12, "Hunter Killer (Hydralisk)", "Hero", P8);
		CreateUnit(10, "Devouring One (Zergling)", "HZ", P8);
		CreateUnit(10, "Devouring One (Zergling)", "Hero", P8);
		Order("Hunter Killer (Hydralisk)", P8, "Hero", Attack, "HZ");
		Order("Devouring One (Zergling)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 680);
	},
	actions = {
		CreateUnit(12, "Hunter Killer (Hydralisk)", "HZ", P8);
		CreateUnit(12, "Hunter Killer (Hydralisk)", "Hero", P8);
		CreateUnit(10, "Kukulza (Guardian)", "HZ", P8);
		CreateUnit(10, "Kukulza (Guardian)", "Hero", P8);
		Order("Hunter Killer (Hydralisk)", P8, "Hero", Attack, "HZ");
		Order("Kukulza (Guardian)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 1040);
	},
	actions = {
		CreateUnit(12, "Torrasque (Ultralisk)", "HZ", P8);
		CreateUnit(12, "Torrasque (Ultralisk)", "Hero", P8);
		CreateUnit(10, "Kukulza (Mutalisk)", "HZ", P8);
		CreateUnit(10, "Kukulza (Mutalisk)", "Hero", P8);
		Order("Torrasque (Ultralisk)", P8, "Hero", Attack, "HZ");
		Order("Kukulza (Mutalisk)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 1570);
	},
	actions = {
		CreateUnit(12, "Torrasque (Ultralisk)", "HZ", P8);
		CreateUnit(12, "Torrasque (Ultralisk)", "Hero", P8);
		CreateUnit(10, "Kukulza (Mutalisk)", "HZ", P8);
		CreateUnit(10, "Kukulza (Mutalisk)", "Hero", P8);
		Order("Torrasque (Ultralisk)", P8, "Hero", Attack, "HZ");
		Order("Kukulza (Mutalisk)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 1960);
	},
	actions = {
		CreateUnit(12, "Fenix (Zealot)", "HZ", P8);
		CreateUnit(12, "Fenix (Zealot)", "Hero", P8);
		CreateUnit(10, "Artanis (Scout)", "HZ", P8);
		CreateUnit(10, "Artanis (Scout)", "Hero", P8);
		Order("Fenix (Zealot)", P8, "Hero", Attack, "HZ");
		Order("Artanis (Scout)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 2335);
	},
	actions = {
		CreateUnit(12, "Fenix (Dragoon)", "HZ", P8);
		CreateUnit(12, "Fenix (Dragoon)", "Hero", P8);
		CreateUnit(10, "Artanis (Scout)", "HZ", P8);
		CreateUnit(10, "Artanis (Scout)", "Hero", P8);
		Order("Fenix (Dragoon)", P8, "Hero", Attack, "HZ");
		Order("Artanis (Scout)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 2864);
	},
	actions = {
		CreateUnit(12, "Warbringer (Reaver)", "HZ", P8);
		CreateUnit(12, "Warbringer (Reaver)", "Hero", P8);
		CreateUnit(10, "Danimoth (Arbiter)", "HZ", P8);
		CreateUnit(10, "Danimoth (Arbiter)", "Hero", P8);
		Order("Warbringer (Reaver)", P8, "Hero", Attack, "HZ");
		Order("Danimoth (Arbiter)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 3427);
	},
	actions = {
		CreateUnit(24, "Kukulza (Guardian)", "HZ", P8);
		CreateUnit(24, "Kukulza (Guardian)", "Hero", P8);
		Order("Kukulza (Guardian)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 3914);
	},
	actions = {
		CreateUnit(24, "Mojo (Scout)", "HZ", P8);
		CreateUnit(24, "Mojo (Scout)", "Hero", P8);
		Order("Mojo (Scout)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 4743);
	},
	actions = {
		CreateUnit(24, "Sarah Kerrigan (Ghost)", "HZ", P8);
		CreateUnit(24, "Sarah Kerrigan (Ghost)", "Hero", P8);
		Order("Sarah Kerrigan (Ghost)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 6110);
	},
	actions = {
		CreateUnit(24, "Edmund Duke (Siege Mode)", "HZ", P8);
		CreateUnit(24, "Edmund Duke (Siege Mode)", "Hero", P8);
		CreateUnit(24, "Tom Kazansky (Wraith)", "HZ", P8);
		CreateUnit(24, "Tom Kazansky (Wraith)", "Hero", P8);
		Order("Tom Kazansky (Wraith)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 6730);
	},
	actions = {
		CreateUnit(12, "Hyperion (Battlecruiser)", "HZ", P8);
		CreateUnit(12, "Hyperion (Battlecruiser)", "Hero", P8);
		CreateUnit(24, "Edmund Duke (Siege Tank)", "HZ", P8);
		CreateUnit(24, "Edmund Duke (Siege Tank)", "Hero", P8);
		Order("Hyperion (Battlecruiser)", P8, "Hero", Attack, "HZ");
		Order("Edmund Duke (Siege Tank)", P8, "Hero", Attack, "HZ");
	},
}


Trigger {
	players = {P8},
	conditions = {
		ElapsedTime(Exactly, 7840);
	},
	actions = {
		CreateUnit(12, "Norad II (Battlecruiser)", "HZ", P8);
		CreateUnit(12, "Norad II (Battlecruiser)", "Hero", P8);
		CreateUnit(12, "Hyperion (Battlecruiser)", "CD37", P8);
		CreateUnit(12, "Hyperion (Battlecruiser)", "CD3", P8);
		CreateUnit(12, "Hyperion (Battlecruiser)", "CD4", P8);
		CreateUnit(12, "Hyperion (Battlecruiser)", "CD38", P8);
		CreateUnit(24, "Edmund Duke (Siege Tank)", "HZ", P8);
		CreateUnit(24, "Edmund Duke (Siege Tank)", "Hero", P8);
		Order("Hyperion (Battlecruiser)", P8, "CD3", Attack, "HZ");
		Order("Hyperion (Battlecruiser)", P8, "CD4", Attack, "HZ");
		Order("Hyperion (Battlecruiser)", P8, "CD38", Attack, "HZ");
		Order("Hyperion (Battlecruiser)", P8, "CD37", Attack, "HZ");
		Order("Norad II (Battlecruiser)", P8, "Hero", Attack, "HZ");
		Order("Edmund Duke (Siege Tank)", P8, "Hero", Attack, "HZ");
	},
}




end